### ISSUE TITLE
Use webcodecamjs by file-input method

### ISSUE THREAD

**Issue by rosickey** [andrastoth/webcodecamjs#1]
getUserMedia is still very limited on ios, how can i use webcodecamjs by file-input method

i upload image, webcodecamjs decode it

**Comment by andrastoth** [comment]
Hello,
I created a new version, based on your request. :)
I will publish this version in few days.
Regards
András

**Comment by rosickey** [comment]
Thanks.
Look forward that version.

**Comment by rosickey** [comment]
That version just upload img,

i change 
<input type="button" id="upload" value="upload" onclick="decodeLocalImage();">
to that
<input type="file" id="upload" value="upload" accept="image/*;" capture="camera" onclick="decodeLocalImage();">

i can not get img from camera, just select img from photo library

how can i upload img from camera
