### ISSUE TITLE
Only Secure Origins are Allowed

### ISSUE THREAD

**Issue by XtremeTheory** [andrastoth/webcodecamjs#11]
Getting this when using mobile Chrome browser trying to use the cameras.

PermissionDeniedError - Only secure origins are allowed

**Comment by XtremeTheory** [comment]
Website must have SSL certificates installed for this program to work properly due to recent security changes that Google Chrome has done.  #figureditoutonmyown lol

**Comment by dominik-theConstruct** [comment]
you can always use "localhost" which by default is always considered "secured origin" ;)
