### ISSUE TITLE
Decoding CODE39 barcodes

### ISSUE THREAD

**Issue by gzurru** [andrastoth/webcodecamjs#13]
Dear Andras,
we have tried your JS library, we love it.
There is only a minor problem: CODE39 barcodes used in Italy (https://en.wikipedia.org/wiki/Italian_fiscal_code_card ) seem to be hard to decode and they are normally mistaken for EAN codes.
 
![tessanretr](https://cloud.githubusercontent.com/assets/16479073/12038285/1ba40a8a-ae57-11e5-8486-dfae96725753.jpg)

We would be very greatful if you could help us out.
Many thanks in advance!

**Comment by andrastoth** [comment]
I am happy because you love this library.
In version 2.0.5, I correct this problem.
Please try it out.

Regards
András

**Comment by knightq** [comment]
It doesn't seems to work on online demo :-(
