### ISSUE TITLE
Trying to scan barcodes with android phone(chrome)

### ISSUE THREAD

**Issue by himchev** [andrastoth/webcodecamjs#14]
I'm trying to run any of the examples (i.e. simple_jquery.html) on a mobile device: Sony xperia m4 aqua (Android 5.0 - Chrome 47.0.2526.83)
QRCode scannig is working fine, but I have problem with barcodes.
It gives the following js error:
js/DecoderWorker.js:333 Uncaught TypeError: Cannot read property '0' of undefined
js/DecoderWorker.js:470 Uncaught TypeError: Cannot read property '0' of undefined

On desktop it's working fine and no errors appear in console.

**Comment by mbenchekroun** [comment]
Are you over SSL ?

**Comment by himchev** [comment]
Yes, I am. But I think that's not the problem actually.
I got it work with v2.0.5

**Comment by andrastoth** [comment]
I'm sorry, 
but I'm not able to reproduce the bug
I tried on some android machine. ZTE Blade v5, Teclast Tablet, etc.
<img src="http://atandrastoth.co.uk/doc/20160206_123207.jpg">
Regards
