### ISSUE TITLE
Running the Demo code

### ISSUE THREAD

**Issue by Uma108** [andrastoth/webcodecamjs#15]
Hi Andreas!

Thanks for the great work on the plugin and offering it to the community! I copied all the code to my local drive and am running the demo code but I dont see anything other than the header "Simple initialization with default settings". Not sure what I am missing.
I really want to take the values of the qr code and pass it through a program that will enact a story online. However I am struggling with getting the output from the qr code connected to my own stuff.

Thanks for your help!
Uma

Update: Actually got it to work by trying a different browser. Thanks for the awesome plugin!

**Comment by andrastoth** [comment]
Hello Uma.
The demo should work.
The local library must belong to a local web server folders.

This demo works the same way:
https://andrastoth.github.io/webcodecamjs/

**Comment by Uma108** [comment]
Hi Andreas,

Thanks for the response. the plug in works great on my local drive. I have
a few questions for you.
1. I want to take the output value which shows up in the HTML file as <p id
"scanned-QR"></p> .
2. Place mulitple values of the scanned items in an array which stops based
on a conditional statement.
The problem I am facing is that I am unable to retrieve the value of
"scanned-qr". I tried going to the JS script and thought it might be
getting it from the lastCode variable? I was trying to find where
(scanned-qr) is stored other than the CSS file so I can input it into an
array. However (doucment.getElementbyId(var).value /byTag or a return
variable in a new function) doesn't seem to return the value if i test it
with an alert box or a button.
Any help is much appreciated.

Thanks again, Uma

**Comment by andrastoth** [comment]
Hi,

The problem is the id is not correct:

document.querySelector('#scanned-QR'), not
document.querySelector('#scanned-qr').
But if you want to put values into an array, use the result function.

resultArray = [];
args =
......
        resultFunction: function(res) {
            [].forEach.call(scannerLaser, function(el) {
                fadeOut(el, 0.5);
                setTimeout(function() {
                    fadeIn(el, 0.5);
                }, 300);
            });
            scannedImg.src = res.imgData;
            scannedQR[txt] = res.format + ': ' + res.code;
            resultArray.push(res);
            doSomethingWithResults(resultArray);
        }
...

    function doSomethingWithResults(array){
        //example
        var find = array.find(function(a){return a.code ==
'0123456789012'});
        if(find){
            // dosomething with  find.code, find.format or find.imgData
        }
    }

Regards

András

**Comment by Uma108** [comment]
Thanks so much Andras! Will definitely try it and out. Uma

**Comment by frevacu** [comment]
How to store the data read in a database?
