### ISSUE TITLE
Camara does not work after remove-reCreate the canvas object

### ISSUE THREAD

**Issue by fjaviergc** [andrastoth/webcodecamjs#16]
Hello, I've tried to use your code in a offline webapp. The camera is used in a form where the user can enter and exit as many times as he need. When the user enter in the form, the application inject the html code of the new form and init the decoder object. It runs very well the first time! However, when the user come back (the application clean the DOM) and enter again in the form, where the camera is used, the canvas object does show nothing. However, my phone notify me that Chrome is using the camera.

I've tried to stop the camera before exit from the form, but it did not work... I attach a code where you can test the issue. I have use the "simple_jquery.html" file and modify some things. So you can test easily.

When you open the example you can follow next steps:
- Push New. It will create a canvas HTML element, init the decoder and show the camera. 
- Push Delete. It will stop the camera and delete the canvas HTML element.
- Push New again:
   · What it should happen: the application shoud create a new canvas HTML element, init the decoder and show the camera.
   · What happen: the application create a new canvas HTML element, init the decoder BUT DOES NOT SHOW THE CAMERA. However if you test it using a mobile, it will notify you that the camera is being used!

Thanks in advance!!

[simple_jquery.html.TXT](https://github.com/andrastoth/webcodecamjs/files/116428/simple_jquery.html.TXT)

**Comment by andrastoth** [comment]
Hello,
Add destroy function to webcodecamjquery.js:

```
        isInitialized: function() {
            return initialized;
        } ,
        destroy: function() {
            stop();
            $(video).off();
            sucessLocalDecode = false,
            localImage = false,
            isStreaming = false,
            delayBool = false,
            initialized = false,
            localStream = null;
        }
    });
    $.fn[pluginName] = function(options) {
```
Usage:
```
$("#cmdDelete").click(function(ev){
	objDecoder.destroy();
	$("#canvas2").detach();
});
```
Regards

**Comment by fjaviergc** [comment]
Hello, thanks very much for your help. I've just tried that and it worked fine!

Regards!

**Comment by nandarbin** [comment]
I have implemented Destroy in WebCodeCamJs.js, but the memory in the browser is getting bigger, every time I open the webcam, because DecoderWorker.js more and more in my browser memory integrates with angular 5

how do i fix it ?, thanks

sorry English is not your native language, if there are errors in the question

**Comment by IshanFx** [comment]
I think we need to terminate the decode worker as well.
added this to the previous solution

`destroy: function() {
            stop();
            $(video).off();
            DecodeWorker.terminate();
            sucessLocalDecode = false,
                localImage = false,
                isStreaming = false,
                delayBool = false,
                initialized = false,
                localStream = null;
        },`
