### ISSUE TITLE
very slow on mobile.. 

### ISSUE THREAD

**Issue by defji** [andrastoth/webcodecamjs#19]
Any solution?

**Comment by andrastoth** [comment]
Hello,
Try these settings:

autoBrightnessValue: false,
decodeQRCodeRate: 2,
decodeBarCodeRate: 2,
frameRate: 5,

With these settings cpu usage will be half (compared to default).
I had modified github test page with these settings.
Please try it out.

Regards
András Tóth

**Comment by defji** [comment]
Köszi! Próbálom, amint tudom
