### ISSUE TITLE
Using two different resultFunctions

### ISSUE THREAD

**Issue by elzaresen** [andrastoth/webcodecamjs#2]
How to use two different resultFunctions?

Example: 
var arg1 = {
	resultFunction: function(resText, lastImageSrc) {
		$('body').append($('<li>' + resText + '</li>'));
		var htmldata = resText.split('[');
		console.log(htmldata)
		p2 = htmldata[1].split(', ')
		p1 = htmldata[0].split(', ')
		id = p1[0];
		name = p1[1];
		price = p1[2]
	}
};
var arg2 = {
	resultFunction: function(resText, lastImageSrc) {
		$('body').append($('<li>' + resText + '</li>'));
		var htmldata = resText.split(', ')
		name = htmldata[0]
		price = htmldata[1]
	}
};

if (document.getElementById("red").checked == true){ //checkbox
s = arg1
}else{
s = arg2
};

var decoder = $("canvas").WebCodeCamJQuery(s).data().plugin_WebCodeCamJQuery;

but it doesn't work

**Comment by andrastoth** [comment]
Hi,

You have several options, example:

1.
             $('#red').on('change', function(){
if($(this).prop('checked')){ decoder.options.resultFunction =
function(resText, lastImageSrc) {
             /* if checked do this*/
}
}else{ decoder.options.resultFunction = function(resText, lastImageSrc) {
           /* or not do this*/
}
} }); var decoder =
$("canvas").WebCodeCamJQuery().data().plugin_WebCodeCamJQuery;
$('#red').change();
decoder.init().play();
2.
        var arg = {
        resultFunction =  function(resText, lastImageSrc) {
      if($('#red').prop('checked')){
            /* if checked do this*/
            }else{
          /* or not do this*/
            }
        };
            var decoder =
$("canvas").WebCodeCamJQuery(arg).data().plugin_WebCodeCamJQuery;
decoder.init().play();

2015-09-14 14:51 GMT+02:00 Elzar Esen <notifications@github.com>:

**Comment by elzaresen** [comment]
Tried first option and.....
It worked!
Thank you very much ^_____^
