### ISSUE TITLE
High quality requirements

### ISSUE THREAD

**Issue by RedCrazyMonkey** [andrastoth/webcodecamjs#20]
Hello. I can not configure the plugin. Scanning is successful only with images of very good quality and large size. Are there any requirements to the images? For example, the lack of foreign characters?

**Comment by andrastoth** [comment]
Hello,

The good quality, necessary.
In the case of a camera the most important one the good illumination

Pleas send me some example image.

András

**Comment by RedCrazyMonkey** [comment]
I try scan this pictures with my phone and webcam on PC. Some examples 
![kt5idyevrjs](https://cloud.githubusercontent.com/assets/18009769/13980339/05f5dd8c-f0ef-11e5-96b4-bd9509b4e1e1.jpg)
![zpwk55vubh8](https://cloud.githubusercontent.com/assets/18009769/13980341/05f71e2c-f0ef-11e5-95ce-0d6abc4a1da4.jpg)
![9ltito70itu](https://cloud.githubusercontent.com/assets/18009769/13980342/05f796fe-f0ef-11e5-8d9a-8f6f74ec7c9d.jpg)
![b-kahqwkshg](https://cloud.githubusercontent.com/assets/18009769/13980340/05f5ebc4-f0ef-11e5-9141-1fc1fe3e9232.jpg)

**Comment by andrastoth** [comment]
Hello,
I tried decoding these pictures , with the following options :
args = {
...
width: 1980,
height: 1050,
...}
It has worked in every case, but it was very slow.
When you use camera, you should to set the view finder to the bar code.
This pictures are too big, bar codes are small.

I hope it will help to you,
