### ISSUE TITLE
it works o my phone but none of my friend's

### ISSUE THREAD

**Issue by victorqribeiro** [andrastoth/webcodecamjs#22]
I'm using it with jquery and jquery moblie, it works on my phone but doesn't seem to work on my friend's phones. What am I doing wrong?

**Comment by elgamersitom** [comment]
We need more information, i know that the library wont work on apple devices.

**Comment by victorqribeiro** [comment]
That's alright. I figured it out. I was trying to open the camera on a http
and not every browser supports that. Once I changed to https it worked
fine.
Thanks a lot
Em 02/05/2016 19:52, "elgamersitom" <notifications@github.com> escreveu:

We need more information, i know that the library wont work on apple
devices.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/andrastoth/webcodecamjs/issues/22#issuecomment-216388622>

**Comment by elgamersitom** [comment]
But it was on android devices?

2016-05-02 17:55 GMT-05:00 victorqribeiro <notifications@github.com>:

> That's alright. I figured it out. I was trying to open the camera on a http
> and not every browser supports that. Once I changed to https it worked
> fine.
> Thanks a lot
> Em 02/05/2016 19:52, "elgamersitom" <notifications@github.com> escreveu:
>
> We need more information, i know that the library wont work on apple
> devices.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <
> https://github.com/andrastoth/webcodecamjs/issues/22#issuecomment-216388622
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/andrastoth/webcodecamjs/issues/22#issuecomment-216389248>
>



-- 
Cristian Narváez.
Ingeniero en Multimedia.
Miembro grupo de investigación ACCEDER <http://www.accederresearch.org/>.
Universidad Militar Nueva Granada.
Bogotá-Colombia

**Comment by victorqribeiro** [comment]
Yep.
Em 02/05/2016 19:57, "elgamersitom" <notifications@github.com> escreveu:

**Comment by andrastoth** [comment]
Hi,
Optimal working depend on OS (version) and browser. Please try latest chrome.
On my blade-v working correctly (android 4.2 , chrome).
