### ISSUE TITLE
How to pause the cam after reading a qr code

### ISSUE THREAD

**Issue by fjaviergc** [andrastoth/webcodecamjs#23]
Hi,

My application needs to read a QR, validates this and then shows an error if the QR wasn't the expected one. When that happens I use the pause method and  show a modal form to inform to the user about the error. When the user closes the modal form, the application will execute the play method to continue using the camera and try to read another QR.

At the beginning, I tried to execute the pause method in the resultFunction. Doing that, the camera never paused. I thougth it was possible the camera were paused because of my pause order, but the execution flow try to play it again to continue reading. So, I tried to execute the pause method using a timeout function. It sometimes works fine, but others not. I suppose the problem is the timeout used.

There exist any other better way to control the pause and play after a QR reading?

Thanks in advance!
fjgc

**Comment by andrastoth** [comment]
hello, I'm going to try.

**Comment by andrastoth** [comment]
I had published a new version.
This is a solution for your issue.
