### ISSUE TITLE
"Oh, no" error on chrome using the camera

### ISSUE THREAD

**Issue by fjaviergc** [andrastoth/webcodecamjs#24]
Hi,

The "Oh, no" chrome error appears when the application is executing during a few minutes without read any code.

Have you ever come across with that problem?

Thanks in advance!
fjgc

**Comment by elgamersitom** [comment]
Hello, 

I have this problem only when i'm using my app on android devices. In other issue you can found what variables you should decrease to improve the library performance.

PDT: If you find a way to select the second camera automaticly i will be happy jajaj
Good Look.

**Comment by andrastoth** [comment]
Hello

The new Chrome versions freezing sometimes for me (on all pages). :(

Examples for camera selection:
    /* Select environment camera if available */
    decoder.buildSelectMenu('#camera-select', 'environment|back').init(args);
    /* Select user camera if available */
    decoder.buildSelectMenu('#camera-select', 'user|front').init(args);
    /* Select camera by name */
    decoder.buildSelectMenu('#camera-select', 'facecam').init(args);
    /* Select first camera */
    decoder.buildSelectMenu('#camera-select', 0).init(args);
    /* Select environment camera if available, without visible select menu*/
    decoder.buildSelectMenu(document.createElement('select'), 'environment|back').init().play();

**Comment by andrastoth** [comment]
For optimal working, this plugin requires strong hardware.
To reduce the processor usage, set  lower rate for decoding and displaying.
