### ISSUE TITLE
problem in chrome update

### ISSUE THREAD

**Issue by sun2sun** [andrastoth/webcodecamjs#26]
hi,
after update chrome WebCodeCam it's not work and show two error in console
error 1 : 
main.js:156 MediaStreamTrack.getSources is deprecated. See https://www.chromestatus.com/feature/4765305641369600 for more details.
error 2 :
WebCodeCam.js:71 getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

how can fix this ?
if i see my web site and run this code on SSL ( httpS ) it's work again but i don't want use ssL

please give me new release or hot fix

**Comment by andrastoth** [comment]
Hello 
MediaStreamTrack.getSources is deprecated
Currently It works, but i will update.
Sorry,
this is a new Chrome security policy :(. I can not fix it.
I think on firefox works on http.

**Comment by sun2sun** [comment]
soory for open it again,
i don't know why when use this url 
http://atandrastoth.co.uk/main/pages/plugins/webcodecamjs/
i can't use webcam and show me error 
but
when i use this url 
https://andrastoth.github.io/webcodecamjs/
it run correctly and work 

why ? What is the difference between these two ؟

**Comment by andrastoth** [comment]
Hello,

Your browser does not support getUserMedia via HTTP!\n(see: https://goo.gl/Y0ZkNV)
Sorry, this is a new chrome policy.
Try Firefox it maybe will work.

**Comment by sun2sun** [comment]
Hello,
oh yes , i'm sorry
thanks.
