### ISSUE TITLE
Camera stays on after calling the stop method

### ISSUE THREAD

**Issue by barmatz** [andrastoth/webcodecamjs#3]
I initiate the plugin (using the code provided in the demo), see myself in the video, then call the `stop` method. The video stops, but the webcam stays on.

This happens also on the [demo page](http://atandrastoth.co.uk/main/pages/plugins/webcodecamjs/).

**Comment by barmatz** [comment]
I took the liberty to implement a solution. Called the `stop` method on the stream when it's supposed to be shut off.
See https://github.com/andrastoth/webcodecamjs/pull/4

**Comment by andrastoth** [comment]
Yes it is true.
But I will using another solution because Chrome says:
'MediaStream.stop()' is deprecated and will be removed in M47, around November 2015. Please use 'MediaStream.active' instead.
I will fix it in a few days.
Thank you

**Comment by barmatz** [comment]
Will you be changing it to the `MediaStreamTrack.stop()` method?

[ref](https://developers.google.com/web/updates/2015/07/mediastream-deprecations?hl=en)

**Comment by andrastoth** [comment]
I changed this method to:

        if (localStream) {
            for (var i = 0; i < localStream.getTracks().length; i++) {
                localStream.getTracks()[i].stop();
            }
        }

2015-10-05 2:26 GMT+02:00 Or Barmatz <notifications@github.com>:
