### ISSUE TITLE
QR Code Reader

### ISSUE THREAD

**Issue by yuhaoneo** [andrastoth/webcodecamjs#31]
The webcam was able to capture the QR Code, but in some occasions, the value was incorrect. The value contains alphanumeric text and part of it was replaced by '-'. Anyone knows why it captures differently?

**Comment by andrastoth** [comment]
Hello,
I think, in this case the decoding was wrong. (blurry image or etc.)
I recommend to you, modify the result function with double check.

Regards 
András
