### ISSUE TITLE
Not Working On Mobile

### ISSUE THREAD

**Issue by ericariyanto** [andrastoth/webcodecamjs#32]
Hello, i just try webcodecamjs. When i access from desktop using chrome it working. but when i access on my mobile phone using ucbrowser (android), it is not. Camera didn't show, and i can't find error message. What happen? what should i do? Can you help me?

Nb ": sorry for my bad english

**Comment by andrastoth** [comment]
Hello,
 try chrome browser. But i am not sure, it works properly. It is depend on os version.
Regards,
András

**Comment by ericariyanto** [comment]
Thanks, it works.
