### ISSUE TITLE
Hyperlink result

### ISSUE THREAD

**Issue by zhionn** [andrastoth/webcodecamjs#33]
Hallo Mr.programmer i have something want to ask you and need you need...i use your webcam qr code system...Can you help me to change after scanned the result will display as a hyperlink link because i want use to open the link after i scanned my qr....Mr programmer pls help me T_T i study your coding so long but i still don't know how to change the result caption as a hyperlink...pls T_T my email: zhionn1217@gmail.com

![untitled](https://cloud.githubusercontent.com/assets/25072119/23506788/f65b6086-ff84-11e6-9575-3e5cd9823ef3.png)

**Comment by andrastoth** [comment]
Hello,

here is a simple solution:

modify the result function

...
resultFunction: function(result) {
    var container = document.querySelector("#scanned-QR");
    var item = document.createElement("a");
    item.target = "_blank";
    if (isValidURL(result.code)) {
        item.href = result.code;
    }
    item.innerText = result.format + ": " + result.code;
    container.appendChild(item);
}, 
... 

function isValidURL(str) {
    var regex = /(http|https):\/\/(\w+:{0,1}\w*)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%!\-\/]))?/;
    if (!regex.test(str)) {
        alert("Please enter valid URL.");
        return false;
    } else {
        return true;
    }
}

I hope it will help you.
Regards
András

**Comment by zhionn** [comment]
Mr programmer i still cannot fix this problem yet can you help me fix it?
