### ISSUE TITLE
Chrome android little issue

### ISSUE THREAD

**Issue by lightway28** [andrastoth/webcodecamjs#35]
Hi,
In this demo page https://andrastoth.github.io/webcodecamjs/ (the index.html file) if I use Chrome for android the camera doesn't start when I hit the Play button. In fact the preview is black.
I have to change manually the select box to "camera 1, facing front" and then change again to "camera 0, facing back" and only then the camera will work.
On Firefox there isn't this bug.
You're project is great!
Can you help me?

**Comment by AladinDridi** [comment]
same question  please

**Comment by andrastoth** [comment]
Hello,

My on my phone works correctly.
Sorry I dont know why not work to you.

Regards
András

**Comment by FGIKCM** [comment]
hello,

same issue for me. This did the trick:
```javascript
setTimeout(function() {decoder.play(); }, 2000);
```

(Wait 2 seconds before starting the camera)
