### ISSUE TITLE
Can't read barcode in Firefox

### ISSUE THREAD

**Issue by joroma** [andrastoth/webcodecamjs#43]
Running the site https://atandrastoth.co.uk/main/pages/plugins/webcodecamjs/ in Firefox produces this error: 
>> TypeError: ScanImage.table[x][y] is undefined

and can't read barcode. Chrome works fine

**Comment by andrastoth** [comment]
I can not reproduce the bug on my machines.

[https://atandrastoth.co.uk/doc/noerr1.PNG](url)

[https://atandrastoth.co.uk/doc/noerr2.PNG](url)

**Comment by joroma** [comment]
Can I know what version of firefox you're using?
Here's a screenshot of my screen

![image](https://user-images.githubusercontent.com/5129659/31868236-63b090c8-b7ce-11e7-85dd-d68894a15c85.png)
![firefox dev tool](https://user-images.githubusercontent.com/5129659/31868244-840108c6-b7ce-11e7-91eb-789fed39ff95.PNG)

**Comment by andrastoth** [comment]
So,
I tested some machine with firefox.
It works.
I think something blocking the background workers in your browser.
Regards 
András
