### ISSUE TITLE
<p> content into <input >

### ISSUE THREAD

**Issue by kulamin** [andrastoth/webcodecamjs#44]
Hi,

i want to get the scanned qr value in input box ,means  
`<p id="scanned-QR"></p>` 
i need this in  
`<input type="text" value="scanned-QR value">` 

how can i do this can you please help me for this 

Thank you

**Comment by andrastoth** [comment]
Hello,

Replace in index.html
`<p id="scanned-QR"></p>`
to
`<input id="scanned-QR" type="text" value="">`

and in main.js
all  `scannedQR[txt] ` to  `scannedQR.value`

Regards
