### ISSUE TITLE
Issue in buildSelectMenu when there is several <select> tags in the HTML page

### ISSUE THREAD

**Issue by ArmandDelessert** [andrastoth/webcodecamjs#47]
There is an issue at [the lines 409 and 410](https://github.com/andrastoth/webcodecamjs/blob/aae3baac7a304f8de3b097a1e7b96a271fc3f26d/js/webcodecamjs.js#L409) when there are several `<select>` HTML tags on the page. In this case, the function `Q(selectorVideo)` returns a `NodeList` instead of an unique element and you can not just access to the `innerHTML` like this : `videoSelect.innerHTML = '';`

Here is screenshots when I debug these lines:

![Debug line 409](https://r1ofkq-am3pap001.files.1drv.com/y4mN9XgIcVKmowccqHRoUoDXoUA9FCB7_wGbD6nnam5n_c-Gd7GaQJnJ5XH4R3gmRhj-EUhKZArk8nnBAEbaYNP5g-bUdXNh2D8lOnmicnblJONP3QPZ_tn1ZJSkckJ1h_GScm_e9zB-XRevFUHXWuDEkH-M2KYVfuOIEuX_0C12V2PLa3Nw-z8FeGiKXwLmN2SGBayjhTF1AI1Eb-McaSZTg?width=1316&height=984&cropmode=none)

![Debug line 410](https://r1pqha-am3pap001.files.1drv.com/y4mDwWa5xvUBelK-Q47ZuHzJnwif-bEoa5oBx-7PtKlyRyao7xXUpDcVsXcojDyO0CYbLHAQteskAwyhS4EWOPYjIRLm0rtxKpOuQ9Xy2cgomp4jMgpXmU4r_maZc8PqRdR8Wlb5B7y0hCo36oSbRnJ-0EhQC0XcKgAvBpIDSWXiOSYszRWnjugA_yRV8efA4D7dLotah56eRh5aZRzYMIlKA?width=1316&height=984&cropmode=none)

**Comment by ArmandDelessert** [comment]
To fix the problem, I added a class to the `<select>` tag like this:

    <select class="scanWebCodeCamJS"></select>

And I call the `buildSelectMenu` function like this:

    decoder.buildSelectMenu('select.scanWebCodeCamJS', 'environment|back');

**Comment by andrastoth** [comment]
Hi,

It is not an issue.
Define your querySelector correctly.
if you have more select on the document, you ca use:
'select:nth-of-type(1)' or id or etc.

Like your second comment.

Regards ,
András
