### ISSUE TITLE
FlipHorizontal camera but unflipped QR code

### ISSUE THREAD

**Issue by barbieswimcrew** [andrastoth/webcodecamjs#5]
Hey ya!

I'm curious if it would be possible to flip the camera by setting flipHorizontal = true but still getting scanned qr codes that aren't flipped?

I think a qr - doesn't matter if digitally or printed - will almost always be unflipped. But I guess the usability could while scanning a qr could be optimized if the cam would be flipped horizontally. In that case my right hand would come into focus from right on screen - as it would even be in real life. 

But as far as i was able to test the current version of your great package the qr cannot be scanned anymore after flipping horizontally.

Maybe you'd make that possible :-)

Thank you in advance!

**Comment by andrastoth** [comment]
Hi,
I fixed it.
Thanks.
