### ISSUE TITLE
qrcode that do two different resultFunctions depending on which button I press

### ISSUE THREAD

**Issue by mpanz79** [andrastoth/webcodecamjs#53]
Hello
i'm trying to set 2 different resultFunctions and depending on which button i press the qrcode reader must set one or the other.

I tried passing the function as a parameter (arg) but the object does not work and continues to do the previous action.

I also tried to destroy the object
$("#canvas").WebCodeCamJQuery().data().plugin_WebCodeCamJQuery.destroy();
but then when i create it again with
$("#canvas").WebCodeCamJQuery(arg).data().plugin_WebCodeCamJQuery.play();
it does not work anymore

I attach my script.

Thanks

Best Regards
[simple_jquery.html.txt](https://github.com/andrastoth/webcodecamjs/files/1751503/simple_jquery.html.txt)

**Comment by andrastoth** [comment]
Hello,
Destroy not acceptable in this case.

Try this:
Regards
András

`<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Demo</title>
    </head>
    <body>
    	<h3>Simple initalization with default settings</h3>
        <hr>
        <canvas id="canvas"></canvas>
        <input type="button" value="ARG1" class="code" rel="arg">
		<input type="button" value="ARG2" class="code" rel="arg2">
        <hr>
        <ul></ul>
		<script type="text/javascript" src="js/jquery.js"></script>
        <script type="text/javascript" src="js/qrcodelib.js"></script>
        <script type="text/javascript" src="js/webcodecamjquery.js"></script>
        <script type="text/javascript">
            var arg = {
                resultFunction: function(result) {
                    $('body').append($('<li>' + result.format + ': ' + result.code + '</li>'));
                }
            };
            var arg2 = {
                resultFunction: function(result) {
                    alert(result.format + ': ' + result.code);
                }
            };
            var decoder = $("#canvas").WebCodeCamJQuery(arg).data().plugin_WebCodeCamJQuery.play();
            $('.code').on("click", function() {
                var argomento = $(this).attr("rel");
                if (argomento == "arg") {
                    decoder.options.resultFunction = arg.resultFunction;
                }
                if (argomento == "arg2") {
                    decoder.options.resultFunction = arg2.resultFunction;
                }
                return false;
            });
        </script>
    </body>
</html>`
