### ISSUE TITLE
code128 not Working, Only QR.... 

### ISSUE THREAD

**Issue by dowista** [andrastoth/webcodecamjs#59]
On pc and android barcodes wont work. It is possible to fix it? Only QR codes work good.

**Comment by andrastoth** [comment]
Hello,
I not understand why. It works for me.
![image](https://user-images.githubusercontent.com/2009969/45249714-1f97bd00-b325-11e8-8b85-42f1c97fb44c.png)
![image](https://user-images.githubusercontent.com/2009969/45249730-71404780-b325-11e8-8e9a-dd218e1cea34.png)
![image](https://user-images.githubusercontent.com/2009969/45249759-270b9600-b326-11e8-8a1d-e51ca20952d6.png)
But sometimes the decoding not get correct result.
Multiple decoding, comparing needed.

Regards
