### ISSUE TITLE
disabling beep not working

### ISSUE THREAD

**Issue by barbieswimcrew** [andrastoth/webcodecamjs#6]
Hi,

as I can see disabling the option beep is not quite possible at the moment. Setting it to null or false isn't working due to the fact that this will cause an 404 file not found error.

Kind regards

**Comment by andrastoth** [comment]
Hi,

I fixed it. 
if you don't want play beep sound set beep parameter to false or null.
Thank you.

Regards

**Comment by barbieswimcrew** [comment]
Hi!

This works, thank you! Unfortunately it looks for me that after this fix the flipped qr detection won't work anymore. 

Cheers

**Comment by andrastoth** [comment]
Hi,
I don't understand. I was trying and worked always.
(Flip modified only visual(css), canvas data was not modificated)
Please try again, and if possibly give me more information .
Cheers

2015-11-05 18:38 GMT+01:00 Mrtn Schndlr <notifications@github.com>:
