### ISSUE TITLE
Not working with iQR and SQRC

### ISSUE THREAD

**Issue by interestingpal** [andrastoth/webcodecamjs#62]
Hi,
thankyou for the wonderful plugin, ive noticed the library isnt compatible with certain qr-codes.
the plugin is not working with iQR code.
Please find attached images.

![image](https://user-images.githubusercontent.com/1072293/42222388-213728da-7ee6-11e8-9e13-95ff351f5223.png)
![image](https://user-images.githubusercontent.com/1072293/42222462-58b41c96-7ee6-11e8-963a-2c36ec044962.png)

Best Regards
Daryl

**Comment by andrastoth** [comment]
Hi,
It works for me if resolution is good for decoding.
Tested Win10, Chrome latest.
![image](https://user-images.githubusercontent.com/2009969/45249633-d004c180-b323-11e8-85ed-081db67d66fd.png)
Regards
