### ISSUE TITLE
Source code doesn't work on localhost

### ISSUE THREAD

**Issue by redplane** [andrastoth/webcodecamjs#69]
Hi,

I have tried using this plugin by cloning the github source code.
Then, I hosted the source code on IIS server.

It is very weird that : **The qr code is scanned successfully on your [Demo site](https://atandrastoth.co.uk/main/pages/plugins/webcodecamjs/). But it isn't recognized on local IIS.**

**Comment by andrastoth** [comment]
Hello,
What it's mean: "But it isn't recognized on local IIS."
Use Https.
Regards

**Comment by redplane** [comment]
Thank you. After changing to https, it worked

**Comment by saranyaanjali** [comment]
Hi sir,
this webcodecam.js functionality when I tried from demo able to access my  integrated camera , when i download and using source code its showing unknown facing camera 1  , cant able to scan but  its asking to allow camera access can you please kindly suggest how to work out this please I need urgent requirement ,please kindly do the needful.
