### ISSUE TITLE
1d codes not scanning

### ISSUE THREAD

**Issue by nmelhado** [andrastoth/webcodecamjs#72]
Hi,

I just started using your library and it works beautifully so far on QR codes, but I have yet to successfully pick up a 1d.  I can't figure out why.  I also noticed that setting my options with:
`DecodeQRCodeRate: null`

My full list of options are as follows:

`var args = {
    DecodeQRCodeRate: null,                    // null to disable OR int > 0 !
    DecodeBarCodeRate: 5,                   // null to disable OR int > 0 !
    successTimeout: 500,                    // delay time when decoding is succeed
    codeRepetition: false,                   // accept code repetition true or false
    tryVertical: true,                      // try decoding vertically positioned barcode true or false
    frameRate: 25,                          // 1 - 25
    width: 320,                             // canvas width
    height: 240,                            // canvas height
    constraints: {                          // default constraints
        video: {
            mandatory: {
                maxWidth: 1280,
                maxHeight: 720
            },
            facingMode: { exact: "environment" }
        },
        audio: true
    },
    flipVertical: true,                    // boolean
    flipHorizontal: true,                  // boolean
    zoom: -1,                               // if zoom = -1, auto zoom for optimal resolution else int
    beep: '../src/audio/beep.mp3',                 // string, audio file location
    decoderWorker: '../src/DecoderWorker.js',   // string, DecoderWorker file location
    brightness: 0,                          // int
    autoBrightnessValue: false,             // functional when value autoBrightnessValue is int
    grayScale: false,                       // boolean
    contrast: 0,                            // int
    threshold: 0,                           // int 
    sharpness: [],      // to On declare matrix, example for sharpness ->  [0, -1, 0, -1, 5, -1, 0, -1, 0]
    resultFunction: function(result) {
        /*
            result.format: code format,
            result.code: decoded string,
            result.imgData: decoded image data
        */
        // var aChild = document.createElement('li');
        // aChild[txt] = result.format + ': ' + result.code;
        // document.querySelector('body').appendChild(aChild);
        decoder.stop();
        continueButton.hidden = false;
        continueButton.disabled = false;
        scannerContainer.hidden = true;
        scannerContainer.disabled = true;
        populate(result.code);
    }
};`

I am then initializing using:

`var decoder = new WebCodeCamJS("canvas");

decoder.init(args).play();`

Please let me know what I'm doing wrong.  My primary use for this would be scanning 1d barcodes.

Thanks,
Nicholas

**Comment by andrastoth** [comment]
Hello
I you want to scan barcode:  DecodeQRCodeRate: 5,                    // null to disable OR int > 0 !
