### ISSUE TITLE
The camera stops working when navigating to another tab and come back

### ISSUE THREAD

**Issue by ursuleacv** [andrastoth/webcodecamjs#9]
When I load the demo page and click play button the camera starts and I am able to scan the code, but when I navigate to another tab and come back to the initial page, the camera stops working and the canvas is empty.

**Comment by andrastoth** [comment]
Hi,
Sorry but I don't understand what happens.
I tried with Chrome 46, Firefox 42 and IE edge(latest), android 4.4(chrome).
I'm can't able to reproduce your problem. Everything works fine.

[video from this issue](http://atandrastoth.co.uk/main/pages/plugins/webcodecamjs/try.webm)
